### ISSUE TITLE
How to install and use "DTITools\IVIMTools" package

### ISSUE THREAD

**Issue by AmIsAre17** [mfroeling/DTITools#1]
Dear Dr. Froeling,
Recently, I am following the paper (Orton MR, Collins DJ, Koh D-M, Leach MO. Improved intravoxel incoherent motion analysis of diffusion weighted imaging by data driven Bayesian modeling. Magn. Reson. Med. 2014;71:411–20. doi: 10.1002/mrm.24649.) to do the IVIM fitting and is recommended to try your toolbox "DTITools\IVIMTools\BayesianIVIMFit2". 

I followed the steps to install the toolbox then to use the toolbox. There are some problems which I have no idea to solve.  

**Describe the bug**
The steps I tried:
1) find user directory using "FileNameJoin[{$UserBaseDirectory,` "Application"}]";
2) then copy all the files of your toolbox into the above folder;
3) new *.nb in this folder to run "<<DTITools`", then some error messages showed up:
![111](https://user-images.githubusercontent.com/40189651/41275371-4dd421f2-6e53-11e8-8d6c-cebef46edfab.jpg)

**Expected behavior**
Since I am newcomer to Mathematica and havent find the proper solution to this problem, my purpose is to try BayesianIVIMFit2 function with 3D matrix data (x*y*bvalue) input. I have no clues to use this toolbox, such as how to call the "BayesianIVIMFits2" function. Should I new a *.nb file and then use special or specific codes to call the function? Is there any examples to call "BayesianIVIMFits2" function to do the fitting using DWI images? 
Thanks so much and waiting for your reply.

**Data**
The input data I wanna use is *.mat with size 256*256*16 (x*y*bvalue).

**Desktop :**
 - [Windows 10]
 - Mathematia version 
 - [Mathematica 11.3.0.0]

**Comment by mfroeling** [comment]
The toolbox should load fine. From the error you show i cannot identify the problem.

make sure the toolbox is either in the `&UserBaseDirectory` of `&BaseDirectory`

![dirs](https://user-images.githubusercontent.com/15890391/41297713-0e8317c6-6e60-11e8-9b2c-d64a3d2b2456.PNG)

The folder ..\Applications\DTITools should look like this 

![folders](https://user-images.githubusercontent.com/15890391/41297741-1e7e8278-6e60-11e8-848f-95fcc3dba3b5.PNG)

The notebook you use to process / load your data can be created anywhere you like. 
I would advice to first learn the basic Mathematica language on how to call functions. 
I don't have any example but for your case the code should look something like

`init = IVIMCalc[data, bvalues, {1, .1, 2.5 10^-3, 20 10^-3}];
{fraction, ADC, pseudoDiffusion} = BayesianIVIMFit2[data, bvalues, init];`

Help on the functions can be found by using `?fucntion` or pressing F1 with the function selected. 
You first need to complete the IVIMCalc to get an initialization for the BayesianFit. 

![help](https://user-images.githubusercontent.com/15890391/41297849-5f2cc870-6e60-11e8-8ae7-6b64e5fda2af.PNG)

![image](https://user-images.githubusercontent.com/15890391/41297934-8b40b624-6e60-11e8-9b98-53b6c3aca9b4.png)

**Comment by AmIsAre17** [comment]
Dear Dr. Froeling,
    Thanks so much for your kind reply and tips. I am sorry to reply so late. I have learned some basic knowledge of Mathematica language last week. I also have tried the method you told. 
For **IVIMCalc** function, I have called it successfully by assigning data `Dimesion[data]={16,256,256}`, bval `Dimensions[bval]={16}` and the initial value you provided in the example.
    However, for **BayesianIVIMFit2** function, there is the error message 
![222](https://user-images.githubusercontent.com/40189651/41658037-cc90504a-74c7-11e8-8096-c70dd9464346.jpg)

when I called it using `{fraction, ADC, pseudoDiffusion} = BayesianIVIMFit2[datad, bval, init[[2 ;;]], maak3d1];`, whatever the mask is `Dimensions[maak3d1]={1,256,256};` or `Dimensions[maak]={256,256}` or `Dimensions[maak3dfull]={3,256,256}`. 

Also, I tried to debug the function **BayesianIVIMFit2** , the error message poped up:
![error2](https://user-images.githubusercontent.com/40189651/41658531-3c79e41a-74c9-11e8-8370-9f15a30b9321.jpg)
And in your original function [in the left side], the parameter **mask** marked with red circle should be same, I replaced them [shown in the right side, marked with red circles], I still get stucked in the `CorrectParMap[fitpar, con2e, mask]` line. 
Do you have any suggestion about the problem I encountered？Thanks so much and thanks again for your reply. Still waiting for your reply~
Best Regards
Alice

**Comment by mfroeling** [comment]
I will look into this next week and get back to you.

**Comment by AmIsAre17** [comment]
Okay, no problem. Thanks so much!

**Comment by AmIsAre17** [comment]
Thanks for your update and reply. 
The error still exist, my two kinds of calling codes:
1) `{fraction, ADC, pseudoDiffusion} = 
  BayesianIVIMFit2[data, bval, init[[2 ;;]], maak];` which are following your tips, where `Dimensions[data]={16,256,256}` ---> number of bvalue*x*y; `Dimensions[bval]={16}`,`Dimensions[init[[2;;]]]={3,256,256}` and `Dimensions[maak]={256,256}`
![erro1](https://user-images.githubusercontent.com/40189651/41827682-42c27c68-7863-11e8-97d5-9e14f66036e4.png)
2) `{fraction, ADC, pseudoDiffusion} = 
  BayesianIVIMFit2[data, bval, init[[2 ;;]], maak3dfull];`,where `Dimensions[maak3dfull]={3,256,256}` and other parameters remain unchanged.
![erro3](https://user-images.githubusercontent.com/40189651/41827738-a8dc7bca-7863-11e8-85ea-6b35726af94b.png)

Therefore, I am wondering, is my calling method is wrong? Is there any difference between my calling codes and your successfull codes? Did I midunderstand your tips?

Now, I am stilling trying check line by line. 
Thanks so much.

**Comment by mfroeling** [comment]
Nope you are doing it all fine. This is a different issue, 
It are still issues with the code while handling 2D data, i typically only work with 3D so everything regarding 2D data is poorly tested. 

new commit should fix this new issue. the code should have called data2Dtovector for your case, your input 1. is the correct one.
